CREATE DATABASE IF NOT EXISTS transactions;
USE transactions;

CREATE TABLE IF NOT EXISTS transactions(
    id INT AUTO_INCREMENT PRIMARY KEY,
    amount INT,
    description VARCHAR (255)
);


CREATE USER IF NOT EXISTS 'expense '@'%' IDENTIFIED BY 'EXPENSEApp@1';
GRANT ALL ON TRANSACTIONS .* TO 'expense'@'%';
FLUSH PRIVILEGES;